name = "Pyxill 2"
description = "A simple, beautiful theme for Hugo."

license = "MIT"
source_repo = "https://github.com/azmelanar/hugo-theme-pixyll"
tags = ["blog", "personal", "search", "responsive", "minimal"]
features = ["minimal js", "local fonts", "fast", "responsive", "dark mode", "nord theme palette"]
min_version = "0.65.1"



[author]
    name = "Iacopo Moles"
    homepage = "https://icpmoles.github.io/"


[original]
    author = "Dmitriy Slupytskyi"
    homepage = "https://themes.gohugo.io/pixyll/"
    repo = "https://github.com/azmelanar/hugo-theme-pixyll"
