baseURL = "https://example.com/"
absURL= "https://example.com"
languageCode = "en-en"
title = "Pixyll Test"

contentdir = "content"
publishdir = "public"
builddrafts = false
CanonifyUrls = true
theme = "pixyll"
ignoreFiles = [ "\\.db$"]
pygmentsUseClassic=false
pygmentsStyle="monokai"
pygmentsCodefences=true
#pygmentsOptions="linenos=table"
Paginate= 10

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  bg_color= "#3b4252"
  theme_color= "#4c566a"
  twitter_username = "twittersupport"
  paginate = 10
  description = "blog made with Hugo"
  author = "Your Name"
  banner= "/banner.png"
#RssUrl = "http://otherwebsite.com/rss" 
  
[author]
  name = "Default Author"
	
[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP", "RSS"]

  
[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true 
